import { test, expect } from '@playwright/test';
import { surveyUrl } from '../../utils/surveys';

test('test', async ({ page }) => {
  await page.goto(surveyUrl('all-question-types'));
  await page.locator('.radio_outerCircle__2ZyKa').first().click();
  await page.locator('div').filter({ hasText: /^First Option$/ }).nth(2).click();
  await page.locator('.grid_gridCell__1w0fk').first().click();
  await page.locator('tr:nth-child(3) > td:nth-child(3) > .grid_gridCell__1w0fk').click();
  await page.getByRole('button', { name: 'Yoda' }).click();
  await page.getByRole('button', { name: 'Andor' }).click();
  await page.getByRole('button', { name: 'Darth vader' }).click();
  await page.locator('#nextPageId').click();
  await page.locator('[id="1732205427855-3-1"]').click();
  await page.locator('#nextPageId').click();
  await page.locator('[id="1732205427868"]').getByRole('textbox', { name: 'Write your answer' }).click();
  await page.locator('[id="1732205427868"]').getByRole('textbox', { name: 'Write your answer' }).fill('2');
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(1).fill('1');
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(2).fill('2');
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(3).click();
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(3).fill('3');
  await page.locator('#nextPageId').click();
  await page.getByRole('textbox', { name: 'Value' }).first().click();
  await page.getByRole('textbox', { name: 'Value' }).first().fill('2');
  await page.getByRole('textbox', { name: 'Value' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Value' }).nth(1).fill('3');
  await page.getByRole('textbox', { name: 'Value' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Value' }).nth(2).fill('1');
  await page.getByText('OK').click();
  await page.getByRole('slider').filter({ hasText: '73' }).click();
  await page.getByRole('slider').filter({ hasText: '-' }).click();
  await page.locator('#nextPageId').click();
  await page.getByRole('row', { name: '1 2 3 4 5 6 7 8 9 10' }).click();
  await page.locator('#nextPageId').click();
  await page.getByText('bed').click();
  await page.getByRole('button', { name: 'Strongly agree' }).click();
  await page.getByText('yet.').click();
  await page.getByRole('button', { name: 'Disagree', exact: true }).click();
  await page.getByText('entire').click();
  await page.locator('#nextPageId').click();
  await page.getByRole('spinbutton', { name: 'Value' }).first().click();
  await page.getByRole('spinbutton', { name: 'Value' }).first().fill('3');
  await page.getByRole('spinbutton', { name: 'Value' }).nth(1).click();
  await page.getByRole('spinbutton', { name: 'Value' }).nth(1).fill('4');
  await page.locator('#nextPageId').click();
  await page.getByRole('cell').first().click();
  await page.locator('[id="1732205427914-2-2"]').click();
  await page.locator('[id="1732205427921-1-1"]').getByRole('spinbutton', { name: 'Value' }).click();
  await page.locator('[id="1732205427921-1-1"]').getByRole('spinbutton', { name: 'Value' }).fill('2');
  await page.locator('[id="1732205427921-1-2"]').getByRole('spinbutton', { name: 'Value' }).click();
  await page.locator('[id="1732205427921-1-2"]').getByRole('spinbutton', { name: 'Value' }).fill('2');
  await page.locator('[id="1732205427921-2-1"]').getByRole('spinbutton', { name: 'Value' }).click();
  await page.locator('[id="1732205427921-2-1"]').getByRole('spinbutton', { name: 'Value' }).fill('3');
  await page.locator('[id="1732205427921-2-2"]').getByRole('spinbutton', { name: 'Value' }).click();
  await page.locator('[id="1732205427921-2-2"]').getByRole('spinbutton', { name: 'Value' }).fill('3');
  await page.locator('#nextPageId').click();
  await page.getByText('173').click();
  await page.getByRole('spinbutton', { name: 'Value' }).first().click();
  await page.getByRole('spinbutton', { name: 'Value' }).first().fill('2');
  await page.getByRole('spinbutton', { name: 'Value' }).nth(1).click();
  await page.getByRole('spinbutton', { name: 'Value' }).nth(1).fill('3');
  await page.locator('#nextPageId').click();
  await page.locator('[id="1732205427935_0-3-1"]').click();
  await page.locator('[id="1732205427935_0-2-2"]').click();
  await page.locator('#nextPageId').click();
  await page.locator('[id="1732205427935_1-3-1"]').click();
  await page.getByRole('cell').nth(5).click();
  await page.locator('div').filter({ hasText: /^Next Page$/ }).click();
  await page.locator('#nextPageId').click();
  await page.locator('[id="1732205427935_2-3-2"]').click();
  await page.getByRole('cell').nth(3).click();
  await page.locator('#nextPageId').click();
  await page.locator('.container_imageContainer__32yDh').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByText('a11').click();
  await page.getByText('a24').first().click();
  await page.locator('#nextPageId').click();
  await page.getByText('a23').first().click();
  await page.locator('#nextPageId').click();
  await page.getByText('a23').click();
  await page.locator('#nextPageId').click();
  await page.getByText('a24').click();
  await page.locator('#nextPageId').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByText('Close').click();
  await page.locator('span').nth(5).click();
  await page.locator('div').filter({ hasText: /^2$/ }).nth(2).click();
  await page.locator('[id="1732206077864-1-2"]').click();
  await page.getByRole('button', { name: '1' }).click();
  await page.getByRole('button', { name: '2' }).click();
  await page.getByRole('slider').click();
  await page.getByRole('textbox', { name: 'Write your answer' }).first().click();
  await page.getByRole('textbox', { name: 'Write your answer' }).first().fill('2');
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(1).fill('3');
  await page.getByRole('textbox', { name: 'Value' }).first().click();
  await page.getByRole('textbox', { name: 'Value' }).first().fill('1');
  await page.getByRole('textbox', { name: 'Value' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Value' }).nth(1).fill('2');
  await page.getByRole('row', { name: '1 2 3 4 5 6 7 8 9 10' }).click();
  await page.getByRole('spinbutton', { name: 'Value' }).first().click();
  await page.getByRole('spinbutton', { name: 'Value' }).first().fill('2');
  await page.getByRole('spinbutton', { name: 'Value' }).nth(1).click();
  await page.getByRole('spinbutton', { name: 'Value' }).nth(1).fill('3');
  await page.locator('[id="1732206078022-1-2"]').click();
  await page.getByRole('cell').filter({ hasText: /^$/ }).nth(5).click();
  await page.locator('[id="1732206078045-1-1"]').getByRole('spinbutton', { name: 'Value' }).click();
  await page.locator('[id="1732206078045-1-1"]').getByRole('spinbutton', { name: 'Value' }).fill('1');
  await page.locator('[id="1732206078045-1-2"]').click();
  await page.locator('[id="1732206078045-1-2"]').getByRole('spinbutton', { name: 'Value' }).click();
  await page.locator('[id="1732206078045-1-2"]').getByRole('spinbutton', { name: 'Value' }).fill('2');
  await page.locator('[id="1732206078045-2-1"]').getByRole('spinbutton', { name: 'Value' }).click();
  await page.locator('[id="1732206078045-2-1"]').getByRole('spinbutton', { name: 'Value' }).fill('3');
  await page.locator('[id="1732206078045-2-2"]').getByRole('spinbutton', { name: 'Value' }).click();
  await page.locator('[id="1732206078045-2-2"]').getByRole('spinbutton', { name: 'Value' }).fill('4');
  await page.locator('#nextPageId').click();
  await page.getByText('Close').click();
  await page.locator('span').nth(5).click();
  await page.locator('div').filter({ hasText: /^2$/ }).nth(2).click();
  await page.locator('.grid_gridCell__1w0fk').first().click();
  await page.getByRole('button', { name: '1' }).click();
  await page.getByRole('button', { name: '2' }).click();
  await page.getByRole('slider').click();
  await page.getByRole('textbox', { name: 'Write your answer' }).first().click();
  await page.getByRole('textbox', { name: 'Write your answer' }).first().fill('2');
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(1).fill('2');
  await page.getByRole('textbox', { name: 'Value' }).first().click();
  await page.getByRole('textbox', { name: 'Value' }).first().fill('2');
  await page.getByRole('textbox', { name: 'Value' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Value' }).nth(1).fill('3');
  await page.locator('div:nth-child(9) > div > div').click();
  await page.getByRole('row', { name: '1 2 3 4 5 6 7 8 9 10' }).click();
  await page.getByRole('spinbutton', { name: 'Value' }).first().click();
  await page.getByRole('spinbutton', { name: 'Value' }).first().fill('3');
  await page.getByRole('spinbutton', { name: 'Value' }).nth(1).click();
  await page.getByRole('spinbutton', { name: 'Value' }).nth(1).fill('2');
  await page.getByRole('cell').filter({ hasText: /^$/ }).nth(3).click();
  await page.locator('.maxDiff_row__W7Loe.maxDiff_odd__BYWw4 > .cell-container.maxDiff_right__AAGXM').click();
  await page.locator('[id="1732221791966-1-1"]').getByRole('spinbutton', { name: 'Value' }).click();
  await page.locator('[id="1732221791966-1-1"]').getByRole('spinbutton', { name: 'Value' }).fill('1');
  await page.locator('[id="1732221791966-1-2"]').getByRole('spinbutton', { name: 'Value' }).click();
  await page.locator('[id="1732221791966-1-2"]').getByRole('spinbutton', { name: 'Value' }).fill('2');
  await page.locator('[id="1732221791966-2-1"]').getByRole('spinbutton', { name: 'Value' }).click();
  await page.locator('[id="1732221791966-2-1"]').getByRole('spinbutton', { name: 'Value' }).fill('2');
  await page.locator('.ant-table.ant-table-middle.ant-table-layout-fixed.ant-table-has-fix-left > .ant-table-container > .ant-table-content > table > .ant-table-tbody > tr:nth-child(2) > td:nth-child(3) > div').click();
  await page.locator('[id="1732221791966-2-2"]').getByRole('spinbutton', { name: 'Value' }).click();
  await page.locator('[id="1732221791966-2-2"]').getByRole('spinbutton', { name: 'Value' }).fill('3');
  await page.locator('#nextPageId').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('#nextPageId').first().click();
  await page.locator('img').click();
  await page.getByRole('dialog', { name: 'Select an option to provide' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('#nextPageId').first().click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('span').filter({ hasText: 'Moderately likely' }).first().click();
  await page.locator('#nextPageId').click();
  await page.getByRole('textbox', { name: 'Write your answer' }).first().click();
  await page.getByRole('textbox', { name: 'Write your answer' }).first().fill('1');
  await page.locator('div').filter({ hasText: /^At what price would you think the item is a bargain - a great buy for the money\?$/ }).first().click();
  await page.locator('div').filter({ hasText: /^At what price would you think the item is a bargain - a great buy for the money\?$/ }).first().click();
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(1).fill('2');
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(2).fill('3');
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(3).click();
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(3).fill('4');
  await page.locator('#nextPageId').click();
  await page.getByText('At what price would you begin to think the item is so inexpensive that you').click();
  await page.getByRole('textbox', { name: 'Write your answer' }).first().fill('81');
  await page.getByRole('textbox', { name: 'Write your answer' }).first().press('Tab');
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(1).fill('82');
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(1).press('Tab');
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(2).fill('83');
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(2).press('Tab');
  await page.getByRole('textbox', { name: 'Write your answer' }).nth(3).fill('84');
  await page.locator('#nextPageId').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('span').filter({ hasText: 'Neither likely nor unlikely' }).first().click();
  await page.locator('#nextPageId').click();
  await page.locator('span').nth(5).click();
  await page.locator('#nextPageId').click();
  await page.locator('span').filter({ hasText: 'NO' }).first().click();
  await page.locator('#nextPageId').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('cell').nth(2).click();
  await page.locator('td:nth-child(3) > .grid_gridCell__vaoqZ').click();
  await page.locator('#nextPageId').click();
  await page.getByRole('cell').nth(4).click();
  await page.locator('[id="1732206078239-LIKERT_NO_GRID-5"]').click();
  await page.locator('#nextPageId').click();
  await page.locator('td:nth-child(3) > .grid_gridCell__vaoqZ').click();
  await page.locator('#nextPageId').click();
  await page.locator('td:nth-child(2) > .grid_gridCell__vaoqZ').click();
  await page.locator('#nextPageId').click();
  await page.locator('div').filter({ hasText: /^Submit$/ }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
});